### PR TITLE
Get all chapters stored in the database

### PR DESCRIPTION
**Pull request by depstein**

### CODE REVIEW

**Comment by jayfo** [comment]
I'm going to merge this, but you should seriously consider some simple tests.

Since I'll be continuing to develop on this, the lack of any test coverage means nobody will have any idea if they are accidentally breaking your services.

**Comment by depstein** [comment]
Will do.

**Comment by jayfo** [comment]
I'm refactoring tests now, so you could wait for that, less boilerplate.

**Comment by depstein** [comment]
I'll wait a tad, then. Though another pull incoming...

It's non-trivial to write tests for the Strava endpoints, since those rely on external APIs. I could theoretically integrate my personal account into the tests, or make a dummy account, but that starts to become more trouble.

**Pull request merged**
